### PR TITLE
Allow Symfony 6

### PR DESCRIPTION
**Pull request by barryvdh**
- [x] Wait on https://github.com/asm89/stack-cors/pull/96
- [x] Remove dev-develop

### CODE REVIEW

**Comment by driesvints** [comment]
@barryvdh can you trigger the builds again here please? Then I can maybe look into them.

**Comment by driesvints** [comment]
Cool I think we're ready to release stable versions of `asm89/stack-cors` and this repo for Symfony v6?

**Comment by barryvdh** [comment]
Yeah just did that :) https://github.com/asm89/stack-cors/releases/tag/v2.0.4

**Comment by barryvdh** [comment]
And this is also tagged now: https://github.com/fruitcake/laravel-cors/releases/tag/v2.0.5

**Comment by barryvdh** [comment]
PR for laravel/laravel here: https://github.com/laravel/laravel/pull/5758

**Comment by driesvints** [comment]
Thanks @barryvdh! 🎉

**Pull request merged**
